# Generated by Django 2.2 on 2019-07-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'managed': False, 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterModelOptions(
            name='ratings',
            options={'managed': False, 'verbose_name_plural': 'Ratings'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'managed': False, 'verbose_name_plural': 'Tags'},
        ),
    ]
